# Generated by Django 5.2.7 on 2025-10-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_paid_at_purchaseorder_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'permissions': [('approve_purchaseorder', 'Can approve purchase orders'), ('mark_paid_purchaseorder', 'Can mark purchase orders as paid')]},
        ),
    ]
