# Generated by Django 5.2.7 on 2025-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
