# Generated by Django 5.2.7 on 2026-01-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('inventory', '0004_alter_category_tenant_alter_product_tenant_and_more'),
        ('tenants', '0002_tenant_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['prediction_date']},
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='confidence_interval',
        ),
        migrations.RemoveField(
            model_name='forecastmodel',
            name='accuracy_score',
        ),
        migrations.AddField(
            model_name='forecast',
            name='reasoning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='data_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='predicted_quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='InventoryAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('shrinkage', 'Unexplained Stock Drop'), ('velocity_spike', 'Sudden Sales Spike'), ('stockout_risk', 'Imminent Stockout')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High - Possible Fraud')], max_length=20)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.DeleteModel(
            name='ForecastFeature',
        ),
    ]
