# Generated by Django 5.2.7 on 2026-02-12 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_forecast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodel',
            name='trained_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
