# Generated by Django 5.2.7 on 2025-10-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscription_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='interval',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Subscription duration in days'),
        ),
    ]
