"""
Forecast & Intelligence Views.

This module powers the "AI Dashboard". It aggregates data from the Machine Learning
models (Forecasts) and the Anomaly Detection engine (Alerts) to provide actionable
insights to the store manager.

Key Components:
1.  **Dashboard Endpoint:** A single aggregate endpoint that returns summary stats,
    future sales predictions, and active inventory alerts (shrinkage, spikes).
"""

from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAdminUser
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404
from core.mixins import TenantFilteredViewSet 
from .models import Forecast, InventoryAnomaly, ForecastModel
from .serializers import ForecastDashboardSerializer, InventoryAnomalySerializer
from .tasks import run_analytics_for_all, train_and_detect_anomalies, generate_daily_forecasts
from tenants.models import Tenant

class ForecastViewSet(TenantFilteredViewSet):
    """
    Read-Only ViewSet for Intelligence Data.
    
    This ViewSet does not allow creating or editing forecasts manually (as they 
    are generated by the AI system). It is strictly for viewing predictions 
    and dashboard metrics.
    """
    queryset = Forecast.objects.all()
    serializer_class = ForecastDashboardSerializer
    http_method_names = ['get']

    @action(detail=False, methods=['get'])
    def dashboard(self, request):
        """
        The Main Intelligence Dashboard Endpoint.

        Aggregates three distinct streams of data into a single response 
        to minimize frontend API calls.

        Returns:
            JSON Object with keys:
            - **summary**: Counters for top-level KPI cards (Total Alerts, Critical, etc.).
            - **forecasts**: List of predicted sales for the next 7 days.
            - **alerts**: List of active, unresolved inventory anomalies.
        """
        tenant = request.user.tenant
        
        # 1. Summary Metrics (For the top KPI cards)
        # We use conditional aggregation (Count + Q objects) to get specific stats
        # in a single database query.
        stats = InventoryAnomaly.objects.filter(tenant=tenant, is_resolved=False).aggregate(
            total_alerts=Count('id'),
            critical_alerts=Count('id', filter=Q(severity='high')),
            velocity_spikes=Count('id', filter=Q(anomaly_type='velocity_spike')),
            ghost_stock=Count('id', filter=Q(anomaly_type='shrinkage')),
        )

        # 2. Forecasts (Next 7 days for top items)
        # Select related 'product' to avoid N+1 queries when serializing names
        forecasts = Forecast.objects.filter(tenant=tenant).select_related('product').order_by('prediction_date')[:50]
        
        # 3. Anomalies (Active alerts only)
        # Ordered by Severity (High first) so the most urgent issues appear at the top
        anomalies = InventoryAnomaly.objects.filter(tenant=tenant, is_resolved=False).select_related('product').order_by('-severity', '-detected_at')
        
        return Response({
            "summary": stats,  # <--- Counters for the colored dashboard cards
            "forecasts": ForecastDashboardSerializer(forecasts, many=True).data,
            "alerts": InventoryAnomalySerializer(anomalies, many=True).data
        })
        
        
class TrainModelsView(APIView):
    """
    Manual Trigger for the AI Forecasting Engine.
    """
    permission_classes = [IsAdminUser] # Only System Admins

    def post(self, request):
        print("🧠 [System Admin] Manually triggering global forecast training...")
        
        # Trigger the Celery Task asynchronously
        run_analytics_for_all.delay(sync=False)
        
        return Response({
            "status": "success", 
            "message": "Global Forecast & Anomaly Detection triggered successfully."
        })
        
        
class TrainSingleTenantView(APIView):
    """
    Trigger AI training for a SPECIFIC tenant only.
    """
    permission_classes = [IsAdminUser]
    
    def get(self, request, tenant_id):
        tenant = get_object_or_404(Tenant, id=tenant_id)
        
        # Fetch the latest model info
        latest_model = ForecastModel.objects.filter(
            tenant=tenant, 
            model_type='evolutionary_v1'
        ).first()
        
        return Response({
            "tenant": tenant.name,
            # Return null if never trained
            "last_trained_at": latest_model.trained_at if latest_model else None 
        })

    def post(self, request, tenant_id):
        tenant = get_object_or_404(Tenant, id=tenant_id)
        
        print(f"🧠 [System Admin] Training model for: {tenant.name}...")
        
        # Trigger tasks for THIS tenant only
        train_and_detect_anomalies.delay(tenant.id)
        generate_daily_forecasts.delay(tenant.id)
        
        return Response({
            "status": "success", 
            "message": f"Training started for {tenant.name}."
        })