"""
Forecast & Intelligence Views.

This module powers the "AI Dashboard". It aggregates data from the Machine Learning
models (Forecasts) and the Anomaly Detection engine (Alerts) to provide actionable
insights to the store manager.

Key Components:
1.  **Dashboard Endpoint:** A single aggregate endpoint that returns summary stats,
    future sales predictions, and active inventory alerts (shrinkage, spikes).
"""

from rest_framework.decorators import action
from rest_framework.response import Response
from django.db.models import Count, Q
from core.mixins import TenantFilteredViewSet 
from .models import Forecast, InventoryAnomaly
from .serializers import ForecastDashboardSerializer, InventoryAnomalySerializer

class ForecastViewSet(TenantFilteredViewSet):
    """
    Read-Only ViewSet for Intelligence Data.
    
    This ViewSet does not allow creating or editing forecasts manually (as they 
    are generated by the AI system). It is strictly for viewing predictions 
    and dashboard metrics.
    """
    queryset = Forecast.objects.all()
    serializer_class = ForecastDashboardSerializer
    http_method_names = ['get']

    @action(detail=False, methods=['get'])
    def dashboard(self, request):
        """
        The Main Intelligence Dashboard Endpoint.

        Aggregates three distinct streams of data into a single response 
        to minimize frontend API calls.

        Returns:
            JSON Object with keys:
            - **summary**: Counters for top-level KPI cards (Total Alerts, Critical, etc.).
            - **forecasts**: List of predicted sales for the next 7 days.
            - **alerts**: List of active, unresolved inventory anomalies.
        """
        tenant = request.user.tenant
        
        # 1. Summary Metrics (For the top KPI cards)
        # We use conditional aggregation (Count + Q objects) to get specific stats
        # in a single database query.
        stats = InventoryAnomaly.objects.filter(tenant=tenant, is_resolved=False).aggregate(
            total_alerts=Count('id'),
            critical_alerts=Count('id', filter=Q(severity='high')),
            velocity_spikes=Count('id', filter=Q(anomaly_type='velocity_spike')),
            ghost_stock=Count('id', filter=Q(anomaly_type='shrinkage')),
        )

        # 2. Forecasts (Next 7 days for top items)
        # Select related 'product' to avoid N+1 queries when serializing names
        forecasts = Forecast.objects.filter(tenant=tenant).select_related('product').order_by('prediction_date')[:50]
        
        # 3. Anomalies (Active alerts only)
        # Ordered by Severity (High first) so the most urgent issues appear at the top
        anomalies = InventoryAnomaly.objects.filter(tenant=tenant, is_resolved=False).select_related('product').order_by('-severity', '-detected_at')
        
        return Response({
            "summary": stats,  # <--- Counters for the colored dashboard cards
            "forecasts": ForecastDashboardSerializer(forecasts, many=True).data,
            "alerts": InventoryAnomalySerializer(anomalies, many=True).data
        })