"""
Notifications Views Module.

This module powers the "Notification Center" in the frontend. 
It provides endpoints for users to fetch their alerts (e.g., Low Stock, 
New Orders, Payment Success) and manage their read status.

Key Characteristics:
- **Read-Only Content:** Users cannot create or delete notifications manually.
- **State Management:** Users can only change the state from 'Unread' to 'Read'.
- **User Scoped:** Users only see notifications specifically addressed to them.
"""

from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from core.mixins import TenantFilteredViewSet
from .models import Notification
from .serializers import NotificationSerializer


class NotificationViewSet(TenantFilteredViewSet):
    """
    Manages User Notifications.
    
    This ViewSet is strictly for consumption. It allows users to:
    1. Poll for new notifications.
    2. Mark items as read (individually or in bulk).
    
    The `create`, `update`, and `destroy` actions are intentionally disabled 
    to preserve the integrity of the audit trail.
    """

    serializer_class = NotificationSerializer
    permission_classes = [IsAuthenticated]
    
    pagination_class = None  # Disable pagination for notifications (Real-time feel)

    def get_queryset(self):
        """
        Filters notifications to return ONLY those:
        1. Belonging to the current Tenant (via TenantFilteredViewSet).
        2. Specifically addressed to the logged-in User.
        """
        return Notification.objects.filter(
            recipient=self.request.user
        )

    def create(self, request, *args, **kwargs):
        """
        Disabled Action.
        
        Notifications are generated by system events (Signals/Celery), 
        not via API calls from the frontend.
        """
        return Response(
            {"detail": "Notifications cannot be created via API."},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    def update(self, request, *args, **kwargs):
        """
        Disabled Action.
        
        Content of a notification is immutable once created.
        """
        return Response(
            {"detail": "Notifications cannot be updated via API."},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    def destroy(self, request, *args, **kwargs):
        """
        Disabled Action.
        
        Notifications serve as a history log and cannot be deleted by users.
        """
        return Response(
            {"detail": "Notifications cannot be deleted via API."},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    @action(detail=True, methods=["post"])
    def mark_read(self, request, pk=None):
        """
        Marks a specific notification as 'Read'.
        
        Used when a user clicks on a notification bubble or expands a specific item.
        """
        notification = self.get_object()
        notification.is_read = True
        notification.save(update_fields=["is_read"])

        return Response(
            {"detail": "Notification marked as read."},
            status=status.HTTP_200_OK,
        )

    @action(detail=False, methods=["post"])
    def mark_all_read(self, request):
        """
        Bulk Action: Marks ALL unread notifications as 'Read' for the current user.
        
        Used for the "Mark all as read" button in the UI.
        """
        updated = Notification.objects.filter(
            tenant=request.user.tenant,
            recipient=request.user,
            is_read=False,
        ).update(is_read=True)

        return Response(
            {
                "detail": f"{updated} notifications marked as read."
            },
            status=status.HTTP_200_OK,
        )