# Generated by Django 5.2.7 on 2025-10-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_tenant_product_tenant_supplier_tenant_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
