# Generated by Django 5.2.7 on 2026-02-10 11:54

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_cost_price'),
    ]

    operations = [
        TrigramExtension(),
    ]
