# Generated by Django 5.2.7 on 2026-02-10 12:03

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20260210_1154'),
        ('tenants', '0004_auditlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='sku_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
