# Generated by Django 5.2.7 on 2025-11-01 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Device',
                'verbose_name_plural': 'Sync Devices',
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_server_version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sync Cursor',
                'verbose_name_plural': 'Sync Cursors',
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('result', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.device')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_change_id', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=10)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='sync.syncjob')),
            ],
            options={
                'verbose_name': 'Sync Operation',
                'verbose_name_plural': 'Sync Operations',
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_snapshot', models.JSONField()),
                ('client_payload', models.JSONField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncoperation')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=16)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tenant', 'id'], name='sync_change_tenant__9e533c_idx'), models.Index(fields=['tenant', 'created_at'], name='sync_change_tenant__c13538_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'device_id'], name='sync_device_tenant__31bf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'user'], name='sync_device_tenant__64e343_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('tenant', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='synccursor',
            index=models.Index(fields=['tenant', 'device', 'last_server_version'], name='sync_synccu_tenant__2f516b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='synccursor',
            unique_together={('tenant', 'device')},
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='sync_syncjo_tenant__a49f43_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['sync_job', 'client_change_id'], name='sync_syncop_sync_jo_510ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['sync_job', 'processed'], name='sync_syncop_sync_jo_4cc9d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncoperation',
            unique_together={('sync_job', 'client_change_id')},
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['sync_operation', 'resolved', 'created_at'], name='sync_syncco_sync_op_7d294c_idx'),
        ),
    ]
