# Generated by Django 5.2.7 on 2026-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_device_consecutive_failures_device_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='tmp_id_map',
            field=models.JSONField(blank=True, default=dict, help_text='Maps client tmp_ids to server DB ids'),
        ),
    ]
