# Generated by Django 5.2.7 on 2026-01-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_syncjob_tmp_id_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
