# Generated by Django 5.2.7 on 2025-10-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0002_role_rolepermission_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('tenant', 'username')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
