# Generated by Django 5.2.7 on 2025-10-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
        ('users', '0004_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_tenant_username',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='unique_tenant_email'),
        ),
    ]
