# Generated by Django 5.2.7 on 2025-10-17 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_unique_tenant_username_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('tenant_admin', 'TenantAdmin'), ('manager', 'Manager'), ('staff', 'Staff'), ('finance_officer', 'FinanceOfficer')], default='staff', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
