# Generated by Django 5.2.7 on 2025-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_seed_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_reason',
            field=models.CharField(blank=True, help_text='Reason for reset: self_reset | admin_reset | system_reset', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last password reset was issued', null=True),
        ),
    ]
