# Generated by Django 5.2.7 on 2026-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tos_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tos_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
