# Generated by Django 5.2.7 on 2026-01-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_tos_accepted_at_user_tos_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('tenant_admin', 'TenantAdmin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50, unique=True),
        ),
    ]
